services:
  backend:
    image: rabent0207/final-penet-backend:latest  # build 대신 image
    container_name: spring-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_HOST=172.31.45.114
      - DB_PORT=3306
      - DB_NAME=ssafy
      - DB_USERNAME=ssafy
      - DB_PASSWORD=ssafy
      - JWT_KEY=${JWT_KEY}
      - API_KEY=${API_KEY}
      - cors.allowed.origins=${CORS_ALLOW}
    volumes:
      - gradle-cache:/root/.gradle
    restart: always
    networks:
      - app-network

  frontend:
    image: rabent0207/final-penet-frontend:latest  # build 대신 image
    container_name: vue-frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  gradle-cache:

networks:
  app-network:
    driver: bridge