services:
  backend:
    build:
      context: ./backend
    container_name: spring-backend
    volumes:
      - gradle-cache:/root/.gradle  # Gradle 캐시 볼륨
    restart: always
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # 필요한 환경변수 추가 (DB 설정 등)

  frontend:
    build:
      context: ./frontend/final-front
    container_name: vue-frontend
    restart: always
    ports:
      - "8080:8080"  # 외부 8080 포트를 컨테이너 80 포트에 매핑
    volumes:
      - ./frontend/final-front/nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 마운트
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  gradle-cache:  # 도커 관리 볼륨 정의

networks:
  app-network:
    driver: bridge