services:
  backend:
    build:
      context: ./backend
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # 필요한 환경변수 추가 (DB 설정 등)

  frontend:
    build:
      context: ./frontend/final-front
    container_name: vue-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # SSL 인증서가 있는 경우
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge